version: '3.9'

services:
  dataservice-cache:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - D:\DockerRun\dataservice\redis-data:/data
  dataservice-secure:
    image: dataservice:v1.1
    volumes:
      - D:\DockerRun\dataservice:/app/ext
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    depends_on:
      - dataapi-cache
