version: '3.9'

services:
  dataservice-cache:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - D:\DockerRun\dataservice\redis-data:/data
  dataservice-secure:
    image: dataservice:latest
    volumes:
      - D:\DockerRun\dataservice\secure-logs:/app/logs
      - D:\DockerRun\dataservice\secure-config:/app/config
      - D:\DockerRun\common:/app/common
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    depends_on:
      - dataapi-cache
