# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clientapival.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63lientapival.proto\x12\x0c\x63lientapival\"\x1c\n\x08\x43lientId\x12\x10\n\x08\x63lientid\x18\x01 \x01(\t\"b\n\nClientInfo\x12\x10\n\x08\x63lientid\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\x05\x12\x0e\n\x06\x65xpiry\x18\x04 \x01(\t\x12\x12\n\npermission\x18\x05 \x01(\t\"0\n\nClientCred\x12\x10\n\x08\x63lientid\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"@\n\x0c\x43lientAPIKey\x12\x10\n\x08\x63lientid\x18\x01 \x01(\t\x12\x0e\n\x06\x61pikey\x18\x02 \x01(\t\x12\x0e\n\x06\x65xpiry\x18\x03 \x01(\t\"\x18\n\x06\x41PIKey\x12\x0e\n\x06\x61pikey\x18\x01 \x01(\t\"3\n\x0eVerifiedAPIKey\x12\x0e\n\x06\x61pikey\x18\x01 \x01(\t\x12\x11\n\tassertion\x18\x02 \x01(\t2\xda\x01\n\x0c\x43lientAPIVal\x12>\n\nclientinfo\x12\x16.clientapival.ClientId\x1a\x18.clientapival.ClientInfo\x12\x44\n\x0c\x63lientapikey\x12\x18.clientapival.ClientCred\x1a\x1a.clientapival.ClientAPIKey\x12\x44\n\x0everifiedapikey\x12\x14.clientapival.APIKey\x1a\x1c.clientapival.VerifiedAPIKeyb\x06proto3')



_CLIENTID = DESCRIPTOR.message_types_by_name['ClientId']
_CLIENTINFO = DESCRIPTOR.message_types_by_name['ClientInfo']
_CLIENTCRED = DESCRIPTOR.message_types_by_name['ClientCred']
_CLIENTAPIKEY = DESCRIPTOR.message_types_by_name['ClientAPIKey']
_APIKEY = DESCRIPTOR.message_types_by_name['APIKey']
_VERIFIEDAPIKEY = DESCRIPTOR.message_types_by_name['VerifiedAPIKey']
ClientId = _reflection.GeneratedProtocolMessageType('ClientId', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTID,
  '__module__' : 'clientapival_pb2'
  # @@protoc_insertion_point(class_scope:clientapival.ClientId)
  })
_sym_db.RegisterMessage(ClientId)

ClientInfo = _reflection.GeneratedProtocolMessageType('ClientInfo', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTINFO,
  '__module__' : 'clientapival_pb2'
  # @@protoc_insertion_point(class_scope:clientapival.ClientInfo)
  })
_sym_db.RegisterMessage(ClientInfo)

ClientCred = _reflection.GeneratedProtocolMessageType('ClientCred', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTCRED,
  '__module__' : 'clientapival_pb2'
  # @@protoc_insertion_point(class_scope:clientapival.ClientCred)
  })
_sym_db.RegisterMessage(ClientCred)

ClientAPIKey = _reflection.GeneratedProtocolMessageType('ClientAPIKey', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTAPIKEY,
  '__module__' : 'clientapival_pb2'
  # @@protoc_insertion_point(class_scope:clientapival.ClientAPIKey)
  })
_sym_db.RegisterMessage(ClientAPIKey)

APIKey = _reflection.GeneratedProtocolMessageType('APIKey', (_message.Message,), {
  'DESCRIPTOR' : _APIKEY,
  '__module__' : 'clientapival_pb2'
  # @@protoc_insertion_point(class_scope:clientapival.APIKey)
  })
_sym_db.RegisterMessage(APIKey)

VerifiedAPIKey = _reflection.GeneratedProtocolMessageType('VerifiedAPIKey', (_message.Message,), {
  'DESCRIPTOR' : _VERIFIEDAPIKEY,
  '__module__' : 'clientapival_pb2'
  # @@protoc_insertion_point(class_scope:clientapival.VerifiedAPIKey)
  })
_sym_db.RegisterMessage(VerifiedAPIKey)

_CLIENTAPIVAL = DESCRIPTOR.services_by_name['ClientAPIVal']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLIENTID._serialized_start=36
  _CLIENTID._serialized_end=64
  _CLIENTINFO._serialized_start=66
  _CLIENTINFO._serialized_end=164
  _CLIENTCRED._serialized_start=166
  _CLIENTCRED._serialized_end=214
  _CLIENTAPIKEY._serialized_start=216
  _CLIENTAPIKEY._serialized_end=280
  _APIKEY._serialized_start=282
  _APIKEY._serialized_end=306
  _VERIFIEDAPIKEY._serialized_start=308
  _VERIFIEDAPIKEY._serialized_end=359
  _CLIENTAPIVAL._serialized_start=362
  _CLIENTAPIVAL._serialized_end=580
# @@protoc_insertion_point(module_scope)
