# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_cust.valclient_pb2 as valclient__pb2


class ValclientStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ElaborDetail = channel.unary_unary(
                '/valclient.Valclient/ElaborDetail',
                request_serializer=valclient__pb2.Request.SerializeToString,
                response_deserializer=valclient__pb2.Response.FromString,
                )


class ValclientServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ElaborDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ValclientServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ElaborDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.ElaborDetail,
                    request_deserializer=valclient__pb2.Request.FromString,
                    response_serializer=valclient__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'valclient.Valclient', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Valclient(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ElaborDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/valclient.Valclient/ElaborDetail',
            valclient__pb2.Request.SerializeToString,
            valclient__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
