# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: valclient.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fvalclient.proto\x12\tvalclient\"\x1c\n\x07Request\x12\x11\n\tclient_id\x18\x01 \x01(\t\"a\n\x08Response\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\x05\x12\x0e\n\x06\x65xpiry\x18\x04 \x01(\t\x12\x12\n\npermission\x18\x05 \x01(\t2D\n\tValclient\x12\x37\n\x0c\x45laborDetail\x12\x12.valclient.Request\x1a\x13.valclient.Responseb\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'valclient_pb2'
  # @@protoc_insertion_point(class_scope:valclient.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'valclient_pb2'
  # @@protoc_insertion_point(class_scope:valclient.Response)
  })
_sym_db.RegisterMessage(Response)

_VALCLIENT = DESCRIPTOR.services_by_name['Valclient']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=30
  _REQUEST._serialized_end=58
  _RESPONSE._serialized_start=60
  _RESPONSE._serialized_end=157
  _VALCLIENT._serialized_start=159
  _VALCLIENT._serialized_end=227
# @@protoc_insertion_point(module_scope)
